### ISSUE TITLE
Support 64bit

### ISSUE THREAD

**Issue by ixiDev** [xyoye/ExoFFmpegPlayer#1]
Hi . thanks for this awesome library , please can you build it again to support 64bit or guide me to build it 
Thanks again

**Comment by xyoye** [comment]
As I stated in the readme file, this source code is from mqplayer. Maybe this issue can help you: https://github.com/joffychim/MQPlayer/issues/2. Sorry i can't do more

**Comment by ixiDev** [comment]
Ok thanks , i have found aar and so files that support 64bit

**Comment by YougaKing** [comment]
> Ok thanks , i have found aar and so files that support 64bit

Hello, can you provide some files that support 64 bit devices？
